;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Commentary:

;; This file will be copied to ldefs-boot.el and checked in
;; periodically.

;;; Code:



;;; Generated autoloads from gtd.el

(register-definition-prefixes "gtd" '("cmp-date-property-stamp"))


;;; Generated autoloads from modes/java.el

(autoload 'java-hook "modes/java")


;;; Generated autoloads from modes/jvm.el

(register-definition-prefixes "modes/jvm" '("javap-handler"))


;;; Generated autoloads from modes/c.el

(autoload 'c-ts-setup "modes/c" "\
Sets up Treesitter for C.")
(register-definition-prefixes "modes/c" '("find-header-files"))


;;; Generated autoloads from org-settings.el

(register-definition-prefixes "org-settings" '("gtd-save-org-buffers" "log-todo-next-creation-date" "org-capture-"))


;;; Generated autoloads from modes/ruby.el

(autoload 'dx-ruby-hook "modes/ruby")

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
